# Site settings
title: Notes from the Plant
email: anthony.mujic@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on control systems, industrial automation, ladder logic and agile software development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  AnthonyMujic

# Build settings
markdown: kramdown

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : 'UA-66284288-1'